---
abstract: ~
author:
  - 'Richard Kelsch <rich@rk-internet.com>'
  - 'Richard Kelsch <rich@csst.net>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.08'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Graphics-Framebuffer
no_index:
  directory:
    - examples
    - inc
    - t
requires:
  perl: 5.14.0
resources:
  license: http://dev.perl.org/licenses/
version: 4.03
