---
abstract: 'A Simple Framebuffer Graphics Library'
author:
  - 'Richard Kelsch <rich@rk-internet.com>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
  Imager: 0
  Math::Trig: 0
  Switch: 0
  Sys::Mmap: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Graphics-Framebuffer
no_index:
  directory:
    - t
    - inc
requires:
  perl: 5.014
version: 4.06
